#/bin/bash

# FLAGS=-I
FLAGS=-a
TARGET_SCHEMA=bdt

function import_shapefile {

	shapefile=$1
	table=$(basename $shapefile .SHP | tr '[:upper:]' '[:lower:]')
	shp2pgsql -D -s 2154 $FLAGS -W LATIN1 $shapefile $TARGET_SCHEMA.bdt_$table | psql

}

import_shapefile A_RESEAU_ROUTIER/CHEMIN.SHP
import_shapefile A_RESEAU_ROUTIER/ROUTE.SHP
import_shapefile A_RESEAU_ROUTIER/ROUTE_NOMMEE.SHP
import_shapefile A_RESEAU_ROUTIER/ROUTE_PRIMAIRE.SHP
import_shapefile A_RESEAU_ROUTIER/ROUTE_SECONDAIRE.SHP
import_shapefile A_RESEAU_ROUTIER/SURFACE_ROUTE.SHP
# import_shapefile A_RESEAU_ROUTIER/TOPONYME_COMMUNICATION.SHP
import_shapefile B_VOIES_FERREES_ET_AUTRES/AIRE_TRIAGE.SHP
import_shapefile B_VOIES_FERREES_ET_AUTRES/GARE.SHP
# import_shapefile B_VOIES_FERREES_ET_AUTRES/TOPONYME_FERRE.SHP
import_shapefile B_VOIES_FERREES_ET_AUTRES/TRANSPORT_CABLE.SHP
import_shapefile B_VOIES_FERREES_ET_AUTRES/TRONCON_VOIE_FERREE.SHP
import_shapefile C_TRANSPORT_ENERGIE/CONDUITE.SHP
import_shapefile C_TRANSPORT_ENERGIE/LIGNE_ELECTRIQUE.SHP
import_shapefile C_TRANSPORT_ENERGIE/POSTE_TRANSFORMATION.SHP
import_shapefile C_TRANSPORT_ENERGIE/PYLONE.SHP
import_shapefile D_HYDROGRAPHIE/CANALISATION_EAU.SHP
import_shapefile D_HYDROGRAPHIE/HYDRONYME.SHP
import_shapefile D_HYDROGRAPHIE/POINT_EAU.SHP
import_shapefile D_HYDROGRAPHIE/RESERVOIR_EAU.SHP
import_shapefile D_HYDROGRAPHIE/SURFACE_EAU.SHP
import_shapefile D_HYDROGRAPHIE/TRONCON_COURS_EAU.SHP
import_shapefile E_BATI/BATI_INDIFFERENCIE.SHP
import_shapefile E_BATI/BATI_INDUSTRIEL.SHP
import_shapefile E_BATI/BATI_REMARQUABLE.SHP
import_shapefile E_BATI/CIMETIERE.SHP
import_shapefile E_BATI/CONSTRUCTION_LEGERE.SHP
import_shapefile E_BATI/CONSTRUCTION_LINEAIRE.SHP
import_shapefile E_BATI/CONSTRUCTION_PONCTUELLE.SHP
import_shapefile E_BATI/CONSTRUCTION_SURFACIQUE.SHP
import_shapefile E_BATI/PISTE_AERODROME.SHP
import_shapefile E_BATI/RESERVOIR.SHP
import_shapefile E_BATI/TERRAIN_SPORT.SHP
import_shapefile F_VEGETATION/ZONE_VEGETATION.SHP
import_shapefile G_OROGRAPHIE/LIGNE_OROGRAPHIQUE.SHP
# import_shapefile G_OROGRAPHIE/ORONYME.SHP
import_shapefile H_ADMINISTRATIF/CHEF_LIEU.SHP
import_shapefile H_ADMINISTRATIF/COMMUNE.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_ADMINISTRATIF_MILITAIRE.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_CULTURE_LOISIRS.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_ESPACE_NATUREL.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_GESTION_EAUX.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_HYDROGRAPHIE.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_INDUSTRIEL_COMMERCIAL.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_OROGRAPHIE.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_RELIGIEUX.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_SANTE.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_SCIENCE_ENSEIGNEMENT.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_SPORT.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_TRANSPORT.SHP
# import_shapefile I_ZONE_ACTIVITE/PAI_ZONE_HABITATION.SHP
import_shapefile I_ZONE_ACTIVITE/SURFACE_ACTIVITE.SHP
import_shapefile T_TOPONYMES/LIEU_DIT_HABITE.SHP
import_shapefile T_TOPONYMES/LIEU_DIT_NON_HABITE.SHP
import_shapefile T_TOPONYMES/TOPONYME_DIVERS.SHP
